Day 6/Controllers/RookiesController.cs
using Microsoft.AspNetCore.Mvc;
using D5.Models;
using System.Globalization;
using CsvHelper;
using CsvHelper.TypeConversion;

namespace D5.Controllers;
// [Route("")]
// [Route("NashTech")]
public class RookiesController : Controller
{
    static List<Person> people = new List<Person>
        {
            new Person
            {
                FirstName = "Phuong",
                LastName = "Nguyen Nam",
                Gender = "Male",
                DateOfBirth = new DateTime(2001, 1, 22),
                PhoneNumber = "",
                BirthPlace = "Phu Tho",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Nam",
                LastName = "Nguyen Thanh",
                Gender = "Male",
                DateOfBirth = new DateTime(2001, 1, 20),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Son",
                LastName = "Do Hong",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 11, 6),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Huy",
                LastName = "Nguyen Duc",
                Gender = "Male",
                DateOfBirth = new DateTime(1996, 1, 26),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Hoang",
                LastName = "Phuong Viet",
                Gender = "Male",
                DateOfBirth = new DateTime(1999, 2, 5),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Long",
                LastName = "Lai Quoc",
                Gender = "Male",
                DateOfBirth = new DateTime(1997, 5, 30),
                PhoneNumber = "",
                BirthPlace = "Bac Giang",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Thanh",
                LastName = "Tran Chi",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 9, 18),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
             new Person
            {
                FirstName = "Manh",
                LastName = "Le Duc",
                Gender = "Male",
                DateOfBirth = new DateTime(2001, 4, 22),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
             new Person
            {
                FirstName = "Dung",
                LastName = "Dao Tan",
                Gender = "Male",
                DateOfBirth = new DateTime(2000, 12, 7),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Linh",
                LastName = "Nguyen",
                Gender = "Female",
                DateOfBirth = new DateTime(1996, 1, 27),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            }
        };
    // [Route("rookies")]
    public IActionResult Index()
    {
        return View(people);
    }


    [Route("rookies/male")]
    [Route("rookies/male-members")]
    public IActionResult GetMaleMembers()
    {
        var results = from person in people where person.Gender == "Male" select person;
        // return new ObjectResult(results);
        return Json(results);
    }

    [Route("rookies/oldest")]
    public IActionResult GetOldestMember()
    {
        var maxAge = people.Max(m => m.Age);
        var oldest = people.First(m => m.Age == maxAge);
        // return new ObjectResult(oldest);
        return Json(oldest);
    }

    [Route("rookies/full-name")]
    public IActionResult GetFullName()
    {
        var fullNames = people.Select(m => m.FullName);
        return Json(fullNames);
    }

    [Route("rookies/split-to-group-by-birth-year/")]
    public IActionResult SplitMemberByBirthYear(int year)
    {
        var results = from person in people
                      group person by person.DateOfBirth.Year.CompareTo(year) into grp
                      select new
                      {
                          Key = grp.Key switch
                          {
                              -1 => $"Birth year less than {year}",
                              0 => $"Birth year equal to {year}",
                              1 => $"Birth year greater than {year}",
                              _ => string.Empty
                          },
                          Data = grp.ToList()
                      };

        return Json(results);
    }

    public IActionResult Export()
    {
        var buffer = WriteCsvToMemory(people);
        var memoryStream = new MemoryStream(buffer);
        return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = "export.csv" };
    }

    public byte[] WriteCsvToMemory(List<Person> data)
    {
        using (var stream = new MemoryStream())
        using (var writer = new StreamWriter(stream))
        using (var csvWriter = new CsvWriter(writer, CultureInfo.InvariantCulture))
        {
            var options = new TypeConverterOptions { Formats = new[] { "dd/MM/yyy" } };
            csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime>(options);

            csvWriter.WriteRecords(data);
            writer.Flush();
            return stream.ToArray();
        }
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Person model)
    {
        if (!ModelState.IsValid) return View();
        people.Add(model);
        return RedirectToAction("Index");
    }
    public IActionResult Edit(int index)
    {
        if (index <= 0 && index > people.Count)
            return RedirectToAction("Index");
        var person = people[index - 1];
        var model = new PersonEditModel(person);
        model.Index = index;
        return View(model);
    }

    [HttpPost]
    public IActionResult Edit(PersonEditModel model)
    {
        if (!ModelState.IsValid) return View();
        people[model.Index - 1] = model;
        return RedirectToAction("Index");
    }

    // [HttpPost]
    public IActionResult Delete(int index)
    {
        if (index <= 0 && index > people.Count)
            return RedirectToAction("Index");
        people.RemoveAt(index-1);
        return RedirectToAction("Index");
    }
}

Day 6/Views/Rookies/Edit.cshtml
@model D5.Models.PersonEditModel
@{
    ViewData["Title"] = "Edit Member";
}

<div class="row">
    <div class="col-6 offset-3">
        <h1>@ViewData["Title"]</h1>
        <form asp-controller="Rookies" asp-action="Edit" method="post">
            <div class="form-group mb-2">
                <label asp-for="FirstName"></label>
                <input type="text" asp-for="FirstName" class="form-control" placeholder="First Name">
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="LastName"></label>
                <input type="text" asp-for="LastName" class="form-control" placeholder="Last Name">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Gender"></label>
                <select class="form-control" asp-for="Gender">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Female">Other</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="DateOfBirth"></label>
                <input type="date" asp-for="DateOfBirth" class="form-control" placeholder="Date of Birth">
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="PhoneNumber"></label>
                <input type="number" asp-for="PhoneNumber" class="form-control" placeholder="Phone Number">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="BirthPlace"></label>
                <input type="text" asp-for="BirthPlace" class="form-control" placeholder="Birth Place">
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Index">
                <a class="btn btn-secondary me-2" asp-controller="Rookies" asp-action="Index">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
       
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day 6/Views/Rookies/Index.cshtml
@* @model List<Person> *@

@{
    ViewData["Title"] = "People Page";
}

<div class="text-center">
    <h1 class="display-4">People List</h1>
    @* @Html.ActionLink("Creat New Member", "Creat", "Rookies",null,htmlAttributes: new {@class="btn btn-primary"}) *@
    <a asp-action="Create" asp-controller="Rookies" class="btn btn-success">Creat New Member</a>
    @* <a href="@Url.Action("Creat", "Rookies")" class="btn btn-secondary">Creat New Member</a> *@
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">Age</th>
                <th scope="col">Birth Place</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @for (var index = 1; index <= Model.Count; index++)
                {
                    var person = Model[index - 1];
                    <tr>
                        <th scope="row">@index</th>
                        <td>@person.FullName</td>
                        <td>@person.Gender</td>
                        <td>@person.DateOfBirth.ToString("dd MMM yyyy")</td>
                        <td>@person.Age</td>
                        <td>@person.BirthPlace</td>
                        <td>
                            <a type="button" class="btn btn-sm btn-primary" asp-action="Edit" asp-controller="Rookies"
                        asp-route-index="@index">Edit</a>
                            <a type="button" class="btn btn-sm btn-warning" asp-action="Delete" asp-controller="Rookies"
                                asp-route-index="@index">Delete</a>
                            <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal"
                        data-bs-target="#deleteModal">Delete by Modal</button>
                            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                            <a type="button" class="btn btn-danger" asp-action="Delete" asp-controller="Rookies"
                                        asp-route-index="@index" data-bs-dismiss="modal">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>